parseSpeed:
	krml -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -o ./out/parseSpeed -no-prefix ParseSpeed parseSpeed.fst
parseIndicator:
	krml -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -o ./out/parseIndicator -no-prefix ParseIndicator parseIndicator.fst
parseDoor:
	krml -warn-error +9 -drop WasmSupport -tmpdir ./out -fsopt --cache_dir -fsopt ./out -fsopt --cache_checked_modules -o ./out/parseDoor -no-prefix ParseDoor parseDoor.fst